work/w08b/d2/stretch-practice/build-another-django-app/completed-code/mydevskills/main_app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name="logout"),
    path('', HomeView.as_view(), name='home'),
    path('skills/', SkillListView.as_view(), name='skill_list'),
    path('skills/<int:pk>/', SkillDetailView.as_view(), name='skill_detail'),
    path('skills/create/', SkillCreate.as_view(), name='skill_create'),
]

work/w08b/d2/stretch-practice/build-another-django-app/completed-code/mydevskills/mydevskills/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

work/w08b/d2/stretch-practice/build-another-django-app/completed-code/mydevskills/main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Skill(models.Model):
    SKILL_LEVELS = (
        (1,	'Fundamental Awareness'),
        (2, 'Novice'),
        (3,	'Intermediate'),
        (4,	'Advanced'),
        (5,	'Expert'),
    )
    description = models.TextField(max_length=300)
    skill_level = models.IntegerField(
        choices=SKILL_LEVELS,
        default=1
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def get_absolute_url(self):
        return reverse('skill_list')

work/w08b/d2/stretch-practice/build-another-django-app/completed-code/mydevskills/main_app/forms.py
from django.forms import ModelForm, Form, CharField, PasswordInput

class LoginForm(Form):
    username = CharField(label="User Name", max_length=64)
    password = CharField(widget=PasswordInput())

work/w08b/d2/stretch-practice/build-another-django-app/completed-code/mydevskills/main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from .forms import LoginForm
from .models import Skill

class HomeView(TemplateView):
    template_name = "home.html"

class SkillListView(ListView):
    template_name = 'skills/list.html'
    def get_queryset(self):
        return self.request.user.skill_set.all()

class SkillDetailView(DetailView):
    model = Skill
    template_name = 'skills/detail.html'

class SkillCreate(CreateView):
    model = Skill
    fields = '__all__'
    template_name = 'skills/form.html'
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('skill_list')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            u = form.cleaned_data['username']
            p = form.cleaned_data['password']
            user = authenticate(username = u, password = p)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('skill_list')
                else:
                    print("The account has been disabled.")
            else:
                print("The username and/or password is incorrect.")
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('home')

work/w08b/d2/stretch-practice/build-another-django-app/completed-code/mydevskills/main_app/templates/skills/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Skill Detail</h1>

<table>
    <thead>
        <th>Description</th>
        <th>Skill Level</th>
    </thead>
    <tbody>
        <tr>
            <td>{{skill.description}}</td>
            <td>{{skill.get_skill_level_display}}</td>
        </tr>
    </tbody>
</table>

{% endblock %}

work/w08b/d2/stretch-practice/build-another-django-app/completed-code/mydevskills/main_app/templates/skills/form.html
{% extends 'base.html' %}

{% block content %}
	<form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Add Skill">
  </form>
{% endblock %}

work/w08b/d2/stretch-practice/build-another-django-app/completed-code/mydevskills/main_app/templates/skills/list.html
{% extends 'base.html' %}

{% block content %}

<h1>My Skills</h1>

<table>
    <thead>
        <th>Description</th>
    </thead>
    <tbody>
        {% for skill in skill_list %}
        <tr><td><a href="{% url 'skill_detail' skill.id %}">{{skill.description}}</a></td></tr>
        {% empty %}
        <tr><td>YOU HAVE NO SKILLS</td></tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}